### ISSUE TITLE
Tests don't pass in 4.3 as plone.protect does not contain required functions

### ISSUE THREAD

**Issue by JeffersonBledsoe** [collective/collective.trustedimports#18]
Plone 4.3 uses plone.protect version 2. `safeWrite` and `addTokenToUrl` were introduced in plone.protect version 3.

**Comment by JeffersonBledsoe** [comment]
@djay Thoughts on fixing the plone 4.3 support?

**Comment by djay** [comment]
@JeffersonBledsoe I think it should be easy to put decordator to avoid that test if the right dependencies aren't there. we already use zcml to avoid loading the code.

**Comment by JeffersonBledsoe** [comment]
@djay Which decorator?

**Comment by djay** [comment]
Google unittest skiptest decorator
